# -*- coding: utf-8 -*-
"""localizer.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PRlOsXzow1czYXkhW5yvHYT8U7dU5AyZ
"""

import numpy as np
import cv2 as cv
from skimage import io
#from google.colab.patches import cv2_imshow
import time

input_path=input("Put in the path of the image: ")
#tic=time.time()
raw=io.imread(str(input_path))
rgb=cv.cvtColor(raw, cv.COLOR_BGR2RGB)

shape=rgb.shape

#cv2_imshow(rgb)

#from google.colab import drive
#drive.mount('/content/drive')

"""#X=|G-B| 
#Y=|2G-R-B|
"""

R=rgb[:,:,0]
G=rgb[:,:,1]
B=rgb[:,:,2]
X=abs(G-B)
Y=abs((2*G)-R-B)

"""#Building=1
#Grass=2
#Road=3
"""

clusters=np.zeros((shape[0],shape[1],shape[2]))

"""#grass=Green
#building=Red
#road=Blue
"""

count_grass=0
count_building=0
count_road=0
for m in range(shape[0]):
  for n in range(shape[1]):
    if X[m,n]>=0 and X[m,n]<=80 and Y[m,n]>=12 and Y[m,n]<=85:
      clusters[m,n]=[0,255,0]
      count_grass+=1
    elif X[m,n]>=4 and X[m,n]<=16 and Y[m,n]>=1 and Y[m,n]<=255:
      clusters[m,n]=[0,0,255]
      count_building+=1
    elif X[m,n]>=237 and X[m,n]<=245 and Y[m,n]>=245 and Y[m,n]<=255:
      clusters[m,n]=[255,0,0]
      count_road+=1

#cv2_imshow(clusters)
#cv2_imshow(rgb)

count_array=np.array([count_building,count_grass,count_road])
print(np.argmax(count_array)+1)